name: book_shelf
description: "A flutter learning project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  http: ^1.4.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_generator: ^0.4.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  mockito: ^5.4.4
  hive_test: ^1.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

